#!/usr/bin/env python
'''
    Script to bulk register existing replicas
'''

import csv

from rucio.client import Client

if __name__ == '__main__':

    with open("/opt/rucio/tools/replicas.csv") as f:
        reader = csv.reader(f)
        data = [r for r in reader]

    rucio_client = Client()
    rse = 'DESY-PROMETHEUS'
#    rse = 'DESY-DISCORDIA'
    # replicas to register
    for scope, name, url, bytes, adler32 in data:
        rucio_client.add_replication_rule(
            dids=[{'scope': scope, 'name': name}],
            account='root',
            copies=1,
            rse_expression=rse,
            grouping='NONE',
            weight=None,
            lifetime=None,
            locked=False)
