rucio_host: https://rucio-doma.cern.ch:443
auth_host: https://rucio-doma.cern.ch:443
auth_type: userpass
permission: generic 
schema: generic 
lfn2pfn_algorithm_default: hash
support: https://github.com/rucio/rucio/issues/
support_rucio: https://github.com/rucio/rucio/issues/
